### ISSUE TITLE
Can't check 4–5 last price data points [Firefox]

### ISSUE THREAD

**Issue by akaihola** [jsarenik/price.bublina.eu.org#5]
When hovering on the very right-hand edge of the chart to see the latest prices, the browser activates the vertical scrollbar instead. This is on Firefox and Windows 11.

Today is 2023-11-23, and the last price I can get it to display is 2023-10-25 as seen here:
![image](https://github.com/jsarenik/price.bublina.eu.org/assets/13725/e128b570-76d2-41d6-abaa-de55fe08094e)

If I move the mouse cursor just one pixel to the right, the price disappears and the scroll bar is displayed:
![image](https://github.com/jsarenik/price.bublina.eu.org/assets/13725/a6de430e-e770-442d-b9c2-0fbd0df39484)

**Comment by jsarenik** [comment]
Yes. I experienced this myself, but have no exact idea how to fix it yet.

**Comment by jsarenik** [comment]
Any suggestions are welcome.

**Comment by jsarenik** [comment]
See the result of PR #8 at https://4eb6519d.pricey.pages.dev/

**Comment by jsarenik** [comment]
BTW, at [link above](https://4eb6519d.pricey.pages.dev/) it for me does not show anything, not just log-log of #7 , on Android (it works for me on Chrome Desktop)

**Comment by jsarenik** [comment]
I think it is fixed now by using Bulma CSS and wider margins. How do you like it, @akaihola ?

**Comment by akaihola** [comment]
> How do you like it, @akaihola ?

It works perfectly!
