### ISSUE TITLE
[Feature idea]: Embed zoom setting in URL

### ISSUE THREAD

**Issue by akaihola** [jsarenik/price.bublina.eu.org#6]
- reflect current zoom window in the URL (after click-dragging and/or panning)
- when opening the page with a zoom window in the URL, automatically zoom to that window

**Comment by jsarenik** [comment]
Oops, just noticed this today.

Thank you very much for feed-back and an idea I also like. @akaihola Do you have any particular ideas about how could this be implemented?

**Comment by akaihola** [comment]
> [...] ideas about how could this be implemented?

Probably using [the History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API#using_pushstate). I haven't used it myself, but I've seen websites make use of it.

**Comment by jsarenik** [comment]
This is propably not going to fly since I personally like the simplicity of statelessness in current implementation.
